[tox]
envlist = unified-planning
basepython = python3
skip_missing_interpreters = true
usedevelop = true

[testenv:unified-planning]
changedir = {toxinidir}/tests/
deps =
  pytest
  unified-planning >= 1.1.0
  ..
commands =
  pytest test-simple.py
