name: Check timelimit

on: push

jobs:
  run-tox-test:
    name: Test timelimit on mac and linux
    runs-on: ${{ matrix.version.os }}
    strategy:
      matrix:
        version:
          - {os: ubuntu-latest, python: '3.10'}
          - {os: macos-13, python: '3.10'}
          - {os: macos-14, python: '3.12'}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4


      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version.python }}

      - name: Install dependencies
        run: |
          pip3 install tox
          pip3 install up-fast-downward

      - name: Run basic test 
        run: |

          cd misc/
          tox -e unified-planning


  run-tox-test-windows:
    name: Test wheels on windows
    needs: [build_wheels_windows]
    runs-on: ${{ matrix.version.os }}
    strategy:
      matrix:
        version:
          - {os: windows-2025, python: '3.11'}
          - {os: windows-2022, python: '3.10'}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version.python }}

      - name: Install dependencies
        run: |
          pip3 install tox
          pip3 install up-fast-downward

      - name: Run basic test 
        run: |

          cd misc/
          tox -e unified-planning
