name: Deploy

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build wheel
        run: python3 setup.py bdist_wheel

      - uses: actions/upload-artifact@master
        with:
          name: linux-wheel
          path: dist


  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build wheel
        run: python3 setup.py bdist_wheel

      - uses: actions/upload-artifact@master
        with:
          name: windows-wheel
          path: dist


  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build wheel
        run: python3 setup.py bdist_wheel

      - uses: actions/upload-artifact@master
        with:
          name: macos-wheel
          path: dist


  deploy-pypi:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]
    if: github.ref == 'refs/heads/master' # We only deploy on master commits

    steps:
      - uses: actions/download-artifact@master
        with:
          name: linux-wheel
          path: dist

      - uses: actions/download-artifact@master
        with:
          name: windows-wheel
          path: dist

      - uses: actions/download-artifact@master
        with:
          name: macos-wheel
          path: dist

      - run: ls dist

      # - name: Upload to PyPI
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     password: ${{ secrets.PYPI_API_TOKEN }}
